// The following file has been auto-generated by headerencoder, modifying it may have unintended consequences.
// Generation date: Sun Jun 22 19:23:01 2025
#pragma once
#include <string>
struct ShaderInfo {
	std::string m_name;
	std::string m_source;
	std::int32_t m_samplers;
	std::int32_t m_storageTextures;
	std::int32_t m_storageBuffers;
	std::int32_t m_uniformBuffers;
};
extern const ShaderInfo SpriteBatch_frag_hlsl;
extern const ShaderInfo PrimitiveBatch_frag_hlsl;
extern const ShaderInfo SpriteBatch_vert_hlsl;
extern const ShaderInfo PrimitiveBatch_vert_hlsl;
